name: pyBLOSSUM

channels:
  - defaults

dependencies:
  - python=3.12.3
  - numpy=1.26.4
  - pandas=2.1.1
  - matplotlib=3.8.4
  - seaborn=0.12.2
  - scipy=1.13.0
  - pyqt=5.15.10
  - anaconda::openpyxl=3.0.10